spring:
    application:
        name: log-insight-app
    profiles:
      default: webflux
    main:
      banner-mode: off
      log-startup-info: false
log-insight:
  mcp:
    target-file-path: "logs/app.log"

